### PR TITLE
added folders and files to set up structure of frontend directory

### PR DESCRIPTION
**Pull request by crestrepo12**
added folders (LogIn-user, Users, images, css) and files(AboutUs, LogIn-user, Register-user, Search-users, Sent-message, User-account, User-bio) to set up the structure of frontend directory. All added folders and files are in 'front-end/src' folder.

### CODE REVIEW

**Review by Acostill — COMMENTED** [review]
Can you make sure all of the folders are in lowercase while the jsx components stay uppercased without dashes?
Ex. Components/Users/LogIn-user/LogIn-user.jsx --> components/users/login/LoginUser.jsx

**Comment by crestrepo12** [comment]
I will make those changes.

**Comment by crestrepo12** [comment]
I edited the style case of the folders and files. I moved the 'login' folder into 'users' folder. I added `"proxy": "http://localhost:3100/"` to 'frontend/package.json'.  I also edited the folder-file path in 'Home.jsx' according to the new changes. I tested it and it works.

**Review by Acostill — APPROVED** [review]
Thanks for the changes. Everything looks good!

**Pull request merged**
