### PR TITLE
fixed images for users in search list and profile

### PR DESCRIPTION
**Pull request by crestrepo12**
User's images now fill in the container.
Also added new files `SingleMessages.jsx` and `SingleMessage.css`.

### CODE REVIEW

**Review by Acostill — CHANGES_REQUESTED** [review]
Very nice visual changes on the profile cards @crestrepo12 . Because the entire profile card changes on hover, it gives the impression that clicking anywhere on the card should redirect the user. I have a few changes in mind below...

Profile Card Requests:
- Can you convert the entire profile card into a link if the css is going to work this way?
- When the mouse hovers over the profile card image, there is an orange square box that fills in before the rest of the component catches up. Can you make the fade consistent throughout the entire card?

Inbox Requests: 
- Since you created a new SingleMessage component, can you insert the message content into SingleMessage, and then import single message in ThreadMessages

**Comment by crestrepo12** [comment]
There is a default image if the user has not placed an image yet.

**Comment by crestrepo12** [comment]
Will fix and add code for `SingleMessage.jsx` component on a different branch.

**Comment by Acostill** [comment]
Very nice @crestrepo12

**Review by Acostill — APPROVED** [review]

**Pull request merged**
